import '@fontsource/roboto-flex/variable-full.css'
import '@fontsource/fira-code'
import '@fontsource/montserrat/variable.css'
import '@fontsource/montserrat/variable-italic.css'
import './src/styles/global.scss'
import './src/styles/wordpress.scss'